# Numpy Cheatsheet

In [1]:
import numpy as np

In [2]:
# python list
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [3]:
type(my_list)

list

### python list to numpy array

In [4]:
# numpy array
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4, 5])

In [5]:
type(my_array)

numpy.ndarray

### 2d array 

In [6]:
my_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
type(my_matrix)

numpy.ndarray

In [8]:
# dimention of array
my_matrix.ndim

2

In [9]:
# shape of matrix
my_matrix.shape

(3, 3)

### numpy common meathods

In [10]:
# arange meathod of array creation 
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# even only
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
# array creation with zeros
# 1d array
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
# 2d array
np.zeros((5,3))
# 3d 
# np.zeros((5,3,5))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# array creation with ones
# 1d array
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### random numbers

In [15]:
np.random.rand(5)

array([0.70628618, 0.26265058, 0.57041254, 0.37012696, 0.77150759])

In [16]:
np.random.rand(2,3)

array([[0.97522405, 0.68587242, 0.36461447],
       [0.8877917 , 0.49950789, 0.74535112]])

In [17]:
# within a spacificed range
# 2x2 matrix with range of 1 -20
np.random.randint(1,20,(2,2))

array([[ 4,  8],
       [13, 16]])

In [18]:
# get same randome values always
np.random.seed(10) # can spacify any value but should be same when need
np.random.randint(1,20,(2,2)) # this random values will always be same if seed spacified

array([[10,  5],
       [16,  1]])

### common array meathods

In [19]:
# reshape meathods reshapes dimenshions of array
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr.reshape(2,5) 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [20]:
arr.min() # min
arr.max() # max
arr.mean() # mean
arr.std() # standerd daviation

2.8722813232690143

## selection using indexces

In [21]:
arr = np.random.randint(1,20,10)
arr

array([18, 17, 18,  9, 10,  1, 11,  9,  5, 17])

In [22]:
# np selection is same as python list
arr[5]

1

In [23]:
arr[9]

17

In [24]:
# negitive indexing same starts from end 
arr[-1]

17

In [25]:
# fist element
arr[-10]

18

## slicing 

In [26]:
arr = np.random.randint(1,20,10)
arr

array([ 5, 16, 12, 12,  2,  9,  5, 15, 18, 14])

In [27]:
# from index 3 to 7 (excluded)
arr[3:7]

array([12,  2,  9,  5])

In [28]:
arr[:5]
# same as arr[0:8]

array([ 5, 16, 12, 12,  2])

In [29]:
arr[5:]
# same as arr[5:10]

array([ 9,  5, 15, 18, 14])

In [30]:
# full array
arr[:]

array([ 5, 16, 12, 12,  2,  9,  5, 15, 18, 14])

### slicing in 2d

In [31]:
arr_2d = np.random.randint(1,100,(3,3))
arr_2d

array([[70, 14, 26],
       [14, 93, 87],
       [31, 31, 90]])

In [32]:
# select a singel row at index 1
arr_2d[1]

array([14, 93, 87])

In [33]:
# get a single item
arr_2d[1,2]
# same as arr_2d[1][2]

87

In [34]:
# select a part of matrix -> [row slice , coloumn slice]
arr_2d[0:2,1:]
# selecct first 2 rows and then select from 1st coloumn to last

array([[14, 26],
       [93, 87]])

In [35]:
arr_2d[:,:2]
# arr_2d[:][:2] not same as above

array([[70, 14],
       [14, 93],
       [31, 31]])

## broadcasting

In [36]:
arr = np.random.randint(20,30,10)
arr 

array([21, 29, 24, 22, 26, 27, 28, 28, 29, 22])

In [37]:
# udating list 
arr[3:6] = 10
arr

array([21, 29, 24, 10, 10, 10, 28, 28, 29, 22])

In [38]:
# creating a slice of arr
slice_of_arr = arr[:3]
slice_of_arr

array([21, 29, 24])

In [39]:
# assigning 10 to every element slice array
slice_of_arr[:] = 0
slice_of_arr

array([0, 0, 0])

In [40]:
# hear we updated slice array to 0 but it updated orignal arr 
# this happens beacuse numpy creates refrence to orignal arr when we create a slice 
# if we update slice it will update orignal arr 
arr

array([ 0,  0,  0, 10, 10, 10, 28, 28, 29, 22])

In [41]:
# to solve this refrence issue we will use copy meathod which will not create a refrece to orignal array
arr = np.random.randint(20,30,10)
arr

array([20, 26, 27, 28, 21, 27, 21, 24, 20, 28])

In [42]:
slice_of_arr = arr[:3].copy()
slice_of_arr

array([20, 26, 27])

In [43]:
# updating sliced array every element
slice_of_arr[:]=0
slice_of_arr

array([0, 0, 0])

In [44]:
# here orignal arr is not manipulated when we updated sliced array
arr

array([20, 26, 27, 28, 21, 27, 21, 24, 20, 28])

## condishional querying

In [45]:
arr = np.random.randint(10,30,20)
arr

array([22, 15, 14, 17, 28, 22, 12, 18, 25, 23, 25, 16, 20, 21, 26, 22, 10,
       27, 25, 22])

In [46]:
# returns boolean array 
arr < 20

array([False,  True,  True,  True, False, False,  True,  True, False,
       False, False,  True, False, False, False, False,  True, False,
       False, False])

In [47]:
# create a condishional array
new_arr = arr[arr < 20]
new_arr

array([15, 14, 17, 12, 18, 16, 10])

## operators

In [48]:
arr = np.random.randint(10,30,10)
arr

array([18, 20, 23, 21, 11, 28, 23, 18, 19, 15])

In [49]:
arr + 5
# arr - 5
# arr * 5
# arr / 5

array([23, 25, 28, 26, 16, 33, 28, 23, 24, 20])

In [50]:
arr + arr

array([36, 40, 46, 42, 22, 56, 46, 36, 38, 30])

In [51]:
arr * arr

array([324, 400, 529, 441, 121, 784, 529, 324, 361, 225])

In [52]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [53]:
np.sqrt(arr)

array([4.24264069, 4.47213595, 4.79583152, 4.58257569, 3.31662479,
       5.29150262, 4.79583152, 4.24264069, 4.35889894, 3.87298335])

In [54]:
np.sin(arr)

array([-0.75098725,  0.91294525, -0.8462204 ,  0.83665564, -0.99999021,
        0.27090579, -0.8462204 , -0.75098725,  0.14987721,  0.65028784])

### operations on 2d array

In [55]:
arr_2d = np.random.randint(1,100,(2,2))
arr_2d

array([[ 1, 19],
       [24,  4]])

In [56]:
# get sum of whole array
arr_2d.sum()

48

In [57]:
# axis = 1 for rows 
arr_2d.sum(axis =1)

array([20, 28])

In [58]:
# axis = 0 for coloumns
arr_2d.sum(axis=0)

array([25, 23])